### ISSUE TITLE
Trouble making it work with Webpack

### ISSUE THREAD

**Issue by demiters** [HriBB/react-mdl-extra#17]
I have react-mdl configured and in use without problems but I was unable to make react-mdl-extra work in a similar manner.

I'm getting an error when trying to use a react-mdl-extra component:
```
[1] /home/app/node_modules/react-mdl-extra/lib/Dropdown/Dropdown.css:1
[1] (function (exports, require, module, __filename, __dirname) { .mdl-dropdown {
[1]                                                               ^
[1] SyntaxError: Unexpected token .
[1]     at Object.exports.runInThisContext (vm.js:76:16)
[1]     at Module._compile (module.js:542:28)
[1]     at Module._extensions..js (module.js:579:10)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/home/app/node_modules/babel-register/lib/node.js:152:7)
[1]     at Module.load (module.js:487:32)
[1]     at tryModuleLoad (module.js:446:12)
[1]     at Module._load (module.js:438:3)
[1]     at Function.module._load (/home/app/node_modules/piping/lib/piping.js:218:16)
[1]     at Module.require (module.js:497:17)
[1]     at require (internal/module.js:20:19)
```

I use style-loader!css-loader as my .css loader. What could be wrong?

**Comment by teonji** [comment]
Hi,
I have same issue. Have you some news about that?!
thanks

**Comment by HriBB** [comment]
Probably a webpack issue. This issue looks similar, maybe it can help https://github.com/roylee0704/react-flexbox-grid/issues/28

**Comment by ghost** [comment]
`SyntaxError: Unexpected token .` indicates your bundler is attempting to parse CSS as plain JavaScript.

<img width="548" alt="screen shot 2017-06-07 at 1 33 26 pm" src="https://user-images.githubusercontent.com/440298/26863592-1c1579fe-4b86-11e7-80e7-8acdd0ed43f3.png">
